typedef enum token_types {
	ASSIGNMENT, ADITTION, SUBTRACTION, MULTIPLICATION, REAL_DIVISION, INTEGER_DIVISION, INTEGER_MODULUS,//operadores  7 0-6
	EQ, UEQ, LE, GE, LEQ, GEQ,IN,//comparadores  7 7-13
	NOT, OR, AND, //booleanos    3 14-16
	LPARENTHESES, RPARENTHESES, INDEX_BRACKET, COMMENT_BRACKET, //parentesis 3 17-20
	COMMA, POINT, SEMICOLON, COLON, HAT ,ARRAY,//puntuacion 6 21-26
	begin, CASE, CONST, DO, DOWNTO, ELSE, END, file, FOR, FUNCTION, GOTO, IF, LABEL, NIL, OF, PACKED, 
	PROCEDURE, PROGRAM, RECORD, REPEAT, SET, THEN, TO, TYPE, UNTIL, VAR, WHILE, WITH , INCLUDE, EXIT, DEFINE,  // Reservados 32 27-58
	IDENTIFIER 
	//59
	}token;
